### Raíz
GET http://localhost:1234/

## Auth

### Registro de usuario
POST http://localhost:1234/auth/register
Content-Type: application/json

{
    "username": "Usuario4",
    "password": "123456",
    "email": "correo4@algo.com"
}

### Login de usuario
POST http://localhost:1234/auth/login
Content-Type: application/json

{
    "username": "Usuario4",
    "password": "123456"
}

### Logout
POST http://localhost:1234/auth/logout
Content-Type: application/json

## Movies

### Recuperar todas las películas
GET http://localhost:1234/movies

### Recuperar todas las películas por un género
GET http://localhost:1234/movies?genres=Drama

### Recuperar todas las películas por varios géneros
GET http://localhost:1234/movies?genres=Drama&genres=Crime

### Recuperar por id
GET http://localhost:1234/movies/d866cc04-3d27-48b6-bc63-a896c8a11b9d

### Crear película
POST http://localhost:1234/movies/
Content-Type: application/json

{
    "title": "Película de prueba 2",
    "year": 2010,
    "director": "Nicolás Lastra",
    "duration": 200,
    "poster": "https://i.ebayimg.com/images/g/yokAAOSw8w1YARbm/s-l1200.jpg",
    "rate": 0,
    "genres": [
        "Drama",
        "Romance"
    ]
}

### Update movie
PATCH http://localhost:1234/movies/f7cac7bf-5f5f-452f-99e3-0b193065a74a
Content-Type: application/json

{
    "title": "Película de prueba 2 v2",
    "year": 2026,
    "genres": [
        "Romance",
        "Sci-Fi"
    ]
}